### PR TITLE
Add support for mp4upload.com

### PR DESCRIPTION
**Pull request by inv3rse**
Works fine for me and hopefully for others ;)

### CODE REVIEW

**Comment by khloke** [comment]
Thank you so much for the contribution. I will merge and test it asap!

**Comment by inv3rse** [comment]
Hmm i did not want the second commit to show up in this pull request...
The second is kind of broken

**Comment by khloke** [comment]
I'll revert that part later

**Comment by inv3rse** [comment]
i removed the part that i did not want to show up in this pull request

**Pull request merged**
