### PR TITLE
Firefox port of the addon

### PR DESCRIPTION
**Pull request by maciex**
I created Firefox port of the addon.
From the tests I've done it looks like the main functionality of the add-on is working properly.

There are few issues (tracked in my fork), but most of them are caused by missing Firefox support of some features. Some of them are already fixed in latest Firefox code, some are being worked on by Firefox team.

Functionality I've tested and confirmed to work:
- options
- Kodi remote (play/pause/stop/next/prev, volume), queue, favourites
- context menu on vimeo/youtube links
- youtube module
- vimeo module

### CODE REVIEW

**Comment by khloke** [comment]
Sorry I can't merge this as the additional 'applications' key isn't supported in Chrome. How about I create a fork of my chrome repo and rename it to play-to-kodi-firefox, and you create a pull request into that, how does that sound?

**Comment by maciex** [comment]
I think that would be OK. But I'm not sure if it would be possible to switch master repos in my current fork in GitHub.

**Comment by maciex** [comment]
One more concern... how would you fix/add additional changes to those two repos? Maintaining two separate code instances will require more time. If not supervised properly they will drift apart after some time, new forks and pull requests etc.
I would prefer to stick with one repository for both addons, but somehow have two manifests. Maybe a build/packaging script? Or just two manifest named accordingly, which should be renamed before packaging?

**Comment by maciex** [comment]
@khloke You mentioned that "applications" key is not supported by Chrome. But from my tests it looks like everything will work the same in Chrome even the key is in the manifest.json.

- I checked the command to generate .crx extension file and no warning was shown, also the package installed fine in Chrome.
Command I used to generate .crx:
`google-chrome --pack-extension=./play-to-xbmc-chrome`
 
- I also generated the .crx extension file in Chrome UI and there was no error shown.
- When using "Load unpacked extension..." from Chrome UI I got a warning:
```
There were warnings when trying to install this extension:
Unrecognized manifest key 'applications'.
```

So only in development mode we would get a warning. But it's just a warning and it can be ignored, as we know it does not cause any problems during generation and installation of the extension (based on two first tests  above).

**Comment by martijnvermaat** [comment]
This already works quite well for me in Firefox 46 and I would love to see the same codebase supporting both browsers. Forking should really be a last resort as I imagine it will be a maintenance nightmare.

There are a few issues with the styling (but they could be related to my Firefox theme). Does anyone know how to use the DOM Inspector in Firefox to inspect the extension UI?

**Comment by maciex** [comment]
@martijnvermaat How to debug extension popups is described in [Web Extension help](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging#Debugging_popups)

>

**Comment by maciex** [comment]
@khloke: I added few more fixes and now Firefox port is working fine on latest Firefox version. There are some minor problems, but those will be fixed in future Firefox versions.

Do you consider to merge Firefox port into your repo? I plan to upload the Add-on to [AMO](https://addons.mozilla.org) so other people could use it easily.

**Pull request merged**
